//! `happyview.record`: record writes as the calling script's user, direct
//! local-index writes, and lexicon validation. A thin translator over SDK
//! host wrappers — this crate neither generates SQL nor talks to the network
//! itself.

#![cfg_attr(target_arch = "wasm32", no_std)]

extern crate alloc;

mod validate;

use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;

use happyview_plugin_sdk::host;
use happyview_plugin_sdk::{
    json, library_plugin, ApiExport, ApiSurface, CallContext, CallerBlobUpload, CallerRecordCreate,
    CallerRecordDelete, CallerRecordPut, IndexDelete, IndexPut, PluginError, PluginInfo, RecordRef,
    Value,
};

library_plugin! {
    info: PluginInfo::new("happyview-record", "Record", "0.1.0"),
    surface: surface,
    call: dispatch,
}

fn surface() -> ApiSurface {
    ApiSurface::new("happyview.record")
        .describe("Record writes as the calling user, local index writes, and validation")
        .export(
            ApiExport::function("create")
                .describe("Create a record in the user's own repo")
                .param("collection", "string", "Lexicon collection NSID")
                .param("record", "object", "Record body")
                .param_json(create_opts())
                .returns(record_ref_shape()),
        )
        .export(
            ApiExport::function("put")
                .describe("Create-or-update a record in the user's own repo")
                .param("uri", "string", "AT URI")
                .param("record", "object", "Record body")
                .param_json(put_opts())
                .returns(record_ref_shape()),
        )
        .export(
            ApiExport::function("delete")
                .describe("Delete a record from the user's own repo")
                .param("uri", "string", "AT URI"),
        )
        .export(
            ApiExport::function("upload_blob")
                .describe("Upload a blob to the user's own repo")
                .param(
                    "bytes",
                    "string",
                    "Blob content: a string, or an array of byte values",
                )
                .param("mime_type", "string", "Blob MIME type")
                .returns(json!({"type": "object", "description": "The PDS's blob ref, as-is"})),
        )
        .export(
            ApiExport::function("load")
                .describe("One indexed record by AT URI, or null")
                .param("uri", "string", "AT URI")
                .returns(json!({
                    "type": "object?",
                    "description": "The record envelope: uri, did, collection, rkey, cid, indexed_at and the stored body under record; a PDS write carries its cid at once, indexed_at stays null until the network echoes the record, and a save_local row has neither"
                })),
        )
        .export(
            ApiExport::function("save_local")
                .describe("Write a record straight into the local index, bypassing the PDS")
                .param("collection", "string", "Lexicon collection NSID")
                .param("rkey", "string", "Record key")
                .param("record", "object", "Record body")
                .param("did", "string?", "Repo DID; defaults to the calling user")
                .returns(record_ref_shape()),
        )
        .export(
            ApiExport::function("delete_local")
                .describe("Remove a record from the local index, bypassing the PDS")
                .param("uri", "string", "AT URI"),
        )
        .export(
            ApiExport::function("validate")
                .describe("Normalize a record against its lexicon and check required fields")
                .param("collection", "string", "Lexicon collection NSID")
                .param("record", "object", "Record body"),
        )
        .export(
            ApiExport::function("lexicon")
                .describe("The lexicon document this instance holds for a collection, or null")
                .param("collection", "string", "Lexicon collection NSID")
                .returns(json!({
                    "type": "object?",
                    "description": "The stored lexicon document as uploaded; a record schema sits at defs.main.record"
                })),
        )
}

fn create_opts() -> Value {
    json!({"name": "opts", "type": "object?", "description": "Create options", "properties": [
        {"name": "rkey", "type": "string?", "description": "Record key; generated by the PDS when absent"},
        {"name": "repo", "type": "string?", "description": "Repo DID; defaults to the caller's own, the only repo a caller-acting write can target"},
        {"name": "validate", "type": "boolean?", "description": "Validate locally and on the PDS before sending; default true"}
    ]})
}

fn put_opts() -> Value {
    json!({"name": "opts", "type": "object?", "description": "Put options", "properties": [
        {"name": "swap_cid", "type": "string?", "description": "Refuse unless this is the record's current CID"},
        {"name": "validate", "type": "boolean?", "description": "Validate locally and on the PDS before sending; default true"}
    ]})
}

fn record_ref_shape() -> Value {
    json!({"type": "object", "properties": [
        {"name": "uri", "type": "string"},
        {"name": "cid", "type": "string"}
    ]})
}

fn dispatch(function: &str, args: &[Value], ctx: &CallContext) -> Result<Value, PluginError> {
    match function {
        "create" => create(args),
        "put" => put(args),
        "delete" => delete(args),
        "upload_blob" => upload_blob(args),
        "load" => load(args),
        "save_local" => save_local(args, ctx),
        "delete_local" => delete_local(args),
        "validate" => validate_record(args),
        "lexicon" => lexicon(args),
        other => Err(PluginError::unknown_function(other)),
    }
}

fn create(args: &[Value]) -> Result<Value, PluginError> {
    let collection = str_arg(args, 0, "collection")?;
    let record = record_arg(args, 1)?;
    let opts = opts_arg(args, 2)?;

    let rkey = opts["rkey"].as_str().map(ToString::to_string);
    let repo = opts["repo"].as_str().map(ToString::to_string);
    let should_validate = opts["validate"].as_bool().unwrap_or(true);

    let lexicon = host::lexicon_get(&collection)?.unwrap_or(Value::Null);
    let record = validate::normalize(&lexicon, &collection, record, !should_validate)?;

    let result = host::caller_create_record(&CallerRecordCreate {
        collection,
        rkey,
        repo,
        record,
        validate: should_validate,
    })?;
    Ok(record_ref_value(result))
}

fn put(args: &[Value]) -> Result<Value, PluginError> {
    let uri = str_arg(args, 0, "uri")?;
    let record = record_arg(args, 1)?;
    let opts = opts_arg(args, 2)?;

    let swap_cid = opts["swap_cid"].as_str().map(ToString::to_string);
    let should_validate = opts["validate"].as_bool().unwrap_or(true);

    let collection = collection_from_uri(&uri)?;
    let lexicon = host::lexicon_get(&collection)?.unwrap_or(Value::Null);
    let record = validate::normalize(&lexicon, &collection, record, !should_validate)?;

    let result = host::caller_put_record(&CallerRecordPut {
        uri,
        record,
        swap_cid,
        validate: should_validate,
    })?;
    Ok(record_ref_value(result))
}

fn delete(args: &[Value]) -> Result<Value, PluginError> {
    let uri = str_arg(args, 0, "uri")?;
    host::caller_delete_record(&CallerRecordDelete { uri })?;
    Ok(Value::Null)
}

fn upload_blob(args: &[Value]) -> Result<Value, PluginError> {
    let bytes = bytes_arg(args, 0)?;
    let mime_type = str_arg(args, 1, "mime_type")?;
    host::caller_upload_blob(&CallerBlobUpload { bytes, mime_type })
}

fn load(args: &[Value]) -> Result<Value, PluginError> {
    let uri = str_arg(args, 0, "uri")?;
    Ok(host::records_get(&uri)?.unwrap_or(Value::Null))
}

fn save_local(args: &[Value], ctx: &CallContext) -> Result<Value, PluginError> {
    let collection = str_arg(args, 0, "collection")?;
    let rkey = str_arg(args, 1, "rkey")?;
    let record = record_arg(args, 2)?;
    let did = args
        .get(3)
        .and_then(Value::as_str)
        .map(ToString::to_string)
        .or_else(|| ctx.caller_did.clone())
        .ok_or_else(|| {
            PluginError::bad_input("did is required: pass one, or call this as a user")
        })?;

    let lexicon = host::lexicon_get(&collection)?.unwrap_or(Value::Null);
    let record = validate::normalize(&lexicon, &collection, record, false)?;

    let result = host::records_index_put(&IndexPut {
        collection,
        rkey,
        did: Some(did),
        record,
        // A local-only save never round-tripped through a PDS, so it has no
        // CID to offer; the row carries none until the network echoes it.
        cid: None,
    })?;
    Ok(record_ref_value(result))
}

fn delete_local(args: &[Value]) -> Result<Value, PluginError> {
    let uri = str_arg(args, 0, "uri")?;
    let removed = host::records_index_delete(&IndexDelete { uri })?;
    Ok(Value::Bool(removed))
}

fn validate_record(args: &[Value]) -> Result<Value, PluginError> {
    let collection = str_arg(args, 0, "collection")?;
    let record = record_arg(args, 1)?;
    let lexicon = host::lexicon_get(&collection)?.unwrap_or(Value::Null);
    validate::normalize(&lexicon, &collection, record, false)
}

fn lexicon(args: &[Value]) -> Result<Value, PluginError> {
    let collection = str_arg(args, 0, "collection")?;
    Ok(lexicon_document(host::lexicon_get(&collection)?))
}

/// A collection with no lexicon answers `null`, which Lua reads as `nil`, so
/// a script tests for it with `== nil` rather than for an error.
fn lexicon_document(found: Option<Value>) -> Value {
    found.unwrap_or(Value::Null)
}

fn record_ref_value(record_ref: RecordRef) -> Value {
    json!({"uri": record_ref.uri, "cid": record_ref.cid})
}

fn str_arg(args: &[Value], index: usize, name: &str) -> Result<String, PluginError> {
    args.get(index)
        .and_then(Value::as_str)
        .map(ToString::to_string)
        .ok_or_else(|| PluginError::bad_input(format!("{name} is required")))
}

/// The wire type accepts `bytes` as a JSON string (UTF-8 content) or an array
/// of byte values; this mirrors that here, ahead of the host call, so a
/// malformed blob body fails fast with a script-actionable message rather
/// than a `serde` error surfaced through `HOST_ERROR`.
fn bytes_arg(args: &[Value], index: usize) -> Result<Vec<u8>, PluginError> {
    match args.get(index) {
        Some(Value::String(text)) => Ok(text.clone().into_bytes()),
        Some(Value::Array(items)) => items
            .iter()
            .map(|item| {
                item.as_u64()
                    .filter(|n| *n <= u8::MAX as u64)
                    .map(|n| n as u8)
                    .ok_or_else(|| {
                        PluginError::bad_input("bytes must be an array of byte values (0-255)")
                    })
            })
            .collect(),
        _ => Err(PluginError::bad_input(
            "bytes is required and must be a string or an array of bytes",
        )),
    }
}

fn record_arg(args: &[Value], index: usize) -> Result<Value, PluginError> {
    match args.get(index) {
        Some(Value::Object(map)) => Ok(Value::Object(map.clone())),
        _ => Err(PluginError::bad_input(
            "record is required and must be an object",
        )),
    }
}

/// `opts` is optional, but when a script does pass something it must be a
/// table — a malformed `opts` (a string, say) silently reading as "no
/// options" would hide the mistake rather than reject it.
fn opts_arg(args: &[Value], index: usize) -> Result<&Value, PluginError> {
    match args.get(index) {
        None | Some(Value::Null) => Ok(&Value::Null),
        Some(value @ Value::Object(_)) => Ok(value),
        _ => Err(PluginError::bad_input("opts must be an object")),
    }
}

/// The collection segment of `at://did/collection/rkey`.
fn collection_from_uri(uri: &str) -> Result<String, PluginError> {
    let rest = uri
        .strip_prefix("at://")
        .ok_or_else(|| PluginError::bad_input("uri must start with at://"))?;
    let mut parts = rest.splitn(3, '/');
    let did = parts.next().filter(|s| !s.is_empty());
    let collection = parts.next().filter(|s| !s.is_empty());
    match (did, collection) {
        (Some(_), Some(collection)) => Ok(collection.to_string()),
        _ => Err(PluginError::bad_input(
            "uri must be at://did/collection/rkey",
        )),
    }
}

#[cfg(test)]
mod tests {
    use alloc::vec;

    use super::*;

    #[test]
    fn str_arg_reads_the_indexed_string() {
        let args = [json!("app.test.thing")];
        assert_eq!(str_arg(&args, 0, "collection").unwrap(), "app.test.thing");
    }

    #[test]
    fn str_arg_rejects_a_missing_value() {
        let args: [Value; 0] = [];
        let err = str_arg(&args, 0, "collection").unwrap_err();
        assert_eq!(err.code, "BAD_INPUT");
    }

    #[test]
    fn record_arg_rejects_a_non_object() {
        let args = [Value::Null, json!("not an object")];
        let err = record_arg(&args, 1).unwrap_err();
        assert_eq!(err.code, "BAD_INPUT");
    }

    #[test]
    fn bytes_arg_reads_a_utf8_string() {
        let args = [json!("hello")];
        assert_eq!(bytes_arg(&args, 0).unwrap(), b"hello".to_vec());
    }

    #[test]
    fn bytes_arg_reads_a_byte_array() {
        let args = [json!([0, 159, 146, 150])];
        assert_eq!(bytes_arg(&args, 0).unwrap(), vec![0, 159, 146, 150]);
    }

    #[test]
    fn bytes_arg_rejects_a_missing_value() {
        let args: [Value; 0] = [];
        let err = bytes_arg(&args, 0).unwrap_err();
        assert_eq!(err.code, "BAD_INPUT");
    }

    #[test]
    fn bytes_arg_rejects_a_non_string_non_array() {
        let args = [json!(42)];
        let err = bytes_arg(&args, 0).unwrap_err();
        assert_eq!(err.code, "BAD_INPUT");
    }

    #[test]
    fn bytes_arg_rejects_an_out_of_range_byte_value() {
        let args = [json!([1, 2, 300])];
        let err = bytes_arg(&args, 0).unwrap_err();
        assert_eq!(err.code, "BAD_INPUT");
    }

    #[test]
    fn opts_arg_defaults_to_null_when_absent() {
        let args: [Value; 0] = [];
        assert_eq!(opts_arg(&args, 0).unwrap(), &Value::Null);
    }

    #[test]
    fn opts_arg_defaults_to_null_for_null() {
        let args = [Value::Null];
        assert_eq!(opts_arg(&args, 0).unwrap(), &Value::Null);
    }

    #[test]
    fn opts_arg_passes_through_an_object() {
        let args = [json!({"validate": false})];
        assert_eq!(opts_arg(&args, 0).unwrap(), &json!({"validate": false}));
    }

    #[test]
    fn opts_arg_rejects_a_non_object() {
        let args = [json!("not an object")];
        let err = opts_arg(&args, 0).unwrap_err();
        assert_eq!(err.code, "BAD_INPUT");
    }

    #[test]
    fn lexicon_document_hands_back_the_document_found() {
        let document = json!({
            "lexicon": 1,
            "id": "app.test.thing",
            "defs": {"main": {"type": "record", "key": "tid", "record": {"properties": {}}}}
        });
        assert_eq!(lexicon_document(Some(document.clone())), document);
    }

    #[test]
    fn lexicon_document_is_null_when_none_is_registered() {
        assert_eq!(lexicon_document(None), Value::Null);
    }

    #[test]
    fn lexicon_rejects_a_missing_collection() {
        let args: [Value; 0] = [];
        let err = lexicon(&args).unwrap_err();
        assert_eq!(err.code, "BAD_INPUT");
    }

    #[test]
    fn collection_from_uri_parses_the_middle_segment() {
        let collection = collection_from_uri("at://did:plc:abc/app.test.thing/xyz").unwrap();
        assert_eq!(collection, "app.test.thing");
    }

    #[test]
    fn collection_from_uri_rejects_a_uri_without_the_scheme() {
        let err = collection_from_uri("did:plc:abc/app.test.thing/xyz").unwrap_err();
        assert_eq!(err.code, "BAD_INPUT");
    }

    #[test]
    fn collection_from_uri_rejects_a_uri_missing_a_collection() {
        let err = collection_from_uri("at://did:plc:abc").unwrap_err();
        assert_eq!(err.code, "BAD_INPUT");
    }
}
