case("basic", function() local co = coroutine.create(function(a) local b = coroutine.yield(a + 1); return b * 2 end); local _, x = coroutine.resume(co, 1); local _, y = coroutine.resume(co, 10); return x, y, coroutine.status(co), coroutine.resume(co) end)
case("wrap", function() local gen = coroutine.wrap(function() for i = 1, 3 do coroutine.yield(i) end end); return gen(), gen(), gen() end)
case("wrap_iterator", function() local function range(n) return coroutine.wrap(function() for i = 1, n do coroutine.yield(i) end end) end; local s = 0; for v in range(4) do s = s + v end; return s end)
case("error_in_coroutine", function() local co = coroutine.create(function() error({ code = 7 }) end); local ok, e = coroutine.resume(co); return ok, e.code, coroutine.status(co) end)
case("yield_across_pcall", function() local co = coroutine.wrap(function() local ok, v = pcall(function() return coroutine.yield("y") + 1 end); return ok, v end); local first = co(); return first, co(41) end)
case("isyieldable_running", function() local _, main = coroutine.running(); return main, coroutine.isyieldable(), coroutine.wrap(function() return coroutine.isyieldable() end)() end)
case("yield_outside", function() return coroutine.yield(1) end)
case("close", function() local co = coroutine.create(function() coroutine.yield() end); coroutine.resume(co); return coroutine.close(co), coroutine.status(co) end)
case("wrap_dead", function() local f = coroutine.wrap(function() end); f(); return pcall(f) end)
return report()
