case("error_string", function() return pcall(error, "boom") end)
case("error_string_pos", function() local ok, e = pcall(function() error("boom") end); return ok, type(e), string.find(e, "boom", 1, true) ~= nil, string.find(e, ":%d+: boom") ~= nil end)
case("error_level0", function() return pcall(function() error("plain", 0) end) end)
case("error_level2", function() local function f() error("lvl2", 2) end; local ok, e = pcall(function() f() end); return ok, string.find(e, "lvl2", 1, true) ~= nil end)
case("error_table", function() local ok, e = pcall(function() error({ code = "NO_SESSION", message = "no session" }) end); return ok, type(e), e.code, e.message end)
case("error_table_identity", function() local payload = {}; local ok, e = pcall(error, payload); return e == payload end)
case("error_nil", function() return pcall(error) end)
case("error_number", function() return pcall(error, 42) end)
case("error_with_tostring_meta", function() local ok, e = pcall(error, setmetatable({}, { __tostring = function() return "custom err" end })); return ok, tostring(e) end)
case("pcall_returns", function() return pcall(function() return 1, 2, 3 end) end)
case("pcall_nonfunction", function() return pcall(nil) end)
case("nested_pcall", function() return pcall(pcall, error, "x") end)
case("rethrow", function() local ok, e = pcall(function() local ok2, e2 = pcall(error, { n = 1 }); error(e2) end); return ok, e.n end)
case("xpcall_handler", function() return xpcall(function() error("bad", 0) end, function(m) return "handled: " .. m end) end)
case("xpcall_args", function() return xpcall(function(a, b) return a + b end, print, 1, 2) end)
case("assert_ok", function() return assert(1, "unused"), assert("v") end)
case("assert_fail_msg", function() return pcall(assert, false, "assert msg") end)
case("assert_fail_default", function() return pcall(assert, nil) end)
case("assert_fail_table", function() local ok, e = pcall(assert, false, { code = 1 }); return ok, e.code end)
case("runtime_msg_index", function() local ok, e = pcall(function() local record = nil; return record.uri end); return (string.gsub(e, "^.-:%d+: ", "")) end)
case("runtime_msg_field", function() local ok, e = pcall(function() local row = {}; return row.record.uri end); return (string.gsub(e, "^.-:%d+: ", "")) end)
case("runtime_msg_global", function() local ok, e = pcall(function() return undefined_fn() end); return (string.gsub(e, "^.-:%d+: ", "")) end)
case("runtime_msg_upvalue", function() local up; local ok, e = pcall(function() return up.x end); return (string.gsub(e, "^.-:%d+: ", "")) end)
case("runtime_msg_concat", function() local ok, e = pcall(function() local s = nil; return "a" .. s end); return (string.gsub(e, "^.-:%d+: ", "")) end)
case("runtime_msg_arith", function() local ok, e = pcall(function() local t = {}; return t.count + 1 end); return (string.gsub(e, "^.-:%d+: ", "")) end)
case("runtime_msg_compare", function() local ok, e = pcall(function() return {} < 1 end); return (string.gsub(e, "^.-:%d+: ", "")) end)
case("runtime_msg_badarg", function() local ok, e = pcall(string.rep); return e end)
case("runtime_msg_badarg2", function() local ok, e = pcall(string.sub, {}); return e end)
case("runtime_msg_badarg_method", function() local ok, e = pcall(function() return ("x"):rep({}) end); return (string.gsub(e, "^.-:%d+: ", "")) end)
case("stack_overflow", function() local function f() return 1 + f() end; local ok, e = pcall(f); return ok, string.find(e, "stack overflow", 1, true) ~= nil end)
case("tostring_error_in_concat", function() return pcall(function() return "x" .. {} end) end)
return report()
