case("math_type", function() return math.type(1), math.type(1.0), math.type("1"), math.type(2^31), math.type(1 // 1), math.type(1 / 1), math.type(3 % 2), math.type(3.0 % 2) end)
case("int_div", function() return 7 // 2, -7 // 2, 7 // -2, 7.0 // 2, -7.5 // 2, 1 // 0.0, -1 // 0.0 end)
case("int_div_zero", function() return 1 // 0 end)
case("mod", function() return 7 % 3, -7 % 3, 7 % -3, 7.5 % 2, -7.5 % 2, 5 % math.huge, -5 % math.huge end)
case("mod_zero", function() return 1 % 0 end)
case("mod_zero_float", function() local r = 1 % 0.0; return r ~= r end)
case("div", function() return 7 / 2, 4 / 2, 1 / 3 end)
case("pow", function() return 2 ^ 10, 2 ^ 0.5, 2 ^ -1, (-8) ^ (1 / 3) ~= (-8) ^ (1 / 3) end)
case("overflow_wrap", function() return math.maxinteger + 1 == math.mininteger, math.maxinteger * 2, math.mininteger - 1, -math.mininteger end)
case("maxmin", function() return math.maxinteger, math.mininteger end)
case("float_int_eq", function() return 1 == 1.0, 2^53 == 2^53 + 1, math.maxinteger + 0.0 == math.maxinteger, math.maxinteger < math.maxinteger + 0.0, 1 < 1.5, "1" == 1 end)
case("table_key_norm", function() local t = {}; t[1.0] = "a"; t[2] = "b"; return t[1], t[2.0], #t, next({ [3.0] = true }) end)
case("tointeger", function() return math.tointeger(3.0), math.tointeger(3.5), math.tointeger("8"), math.tointeger(2^63), math.tointeger("x") end)
case("floor_ceil", function() return math.floor(3.7), math.ceil(3.2), math.floor(-3.5), math.floor(2^62), math.floor(1e100), math.type(math.floor(1e100)) end)
case("misc", function() return math.abs(-3), math.abs(-3.5), math.max(1, 2.5, -1), math.min(3, 1), math.sqrt(16), math.fmod(7, 3), math.fmod(-7, 3), math.pi, math.huge end)
case("abs_minint", function() return math.abs(math.mininteger) end)
case("ult", function() return math.ult(1, -1), math.ult(-1, 1) end)
case("fmod_zero", function() return math.fmod(1, 0) end)
case("modf", function() return math.modf(3.7), math.modf(-3.7), math.modf(5), math.modf(math.huge) end)
case("trig_exp", function() return math.sin(0), math.cos(0), math.exp(0), math.log(8, 2), math.log(100, 10), math.log(1) end)
case("literals", function() return 0xff, 0x7fffffffffffffff, 0xffffffffffffffff, 0x1p4, 1e2, .5, 3., 0xA.8p0, 9223372036854775807, 9223372036854775808 end)
case("float_to_string", function() return 1e15, 1e16, 123456789012345678, 0.1, 1 / 3, 100.0, -0.0, 3.14159265358979, 2^63, 1e300 * 1e10 end)
case("num_str_coerce_concat", function() return 10 .. "", 10.0 .. "", 2^31 .. "" end)
case("for_int", function() local n = 0; for i = 1, 3 do n = n + i end; for i = 10, 1, -3 do n = n + i end; return n end)
case("for_float", function() local out = {}; for i = 1.0, 2.0, 0.5 do out[#out + 1] = i end; return out end)
case("for_overflow", function() local n = 0; for i = math.maxinteger - 1, math.maxinteger do n = n + 1 end; return n end)
case("for_zero_step", function() for i = 1, 2, 0 do end end)
case("arith_on_nil", function() return 1 + nil end)
case("arith_on_string_bad", function() return 1 + "x" end)
case("compare_mixed", function() return 1 < "2" end)
case("float_int_conv_err", function() return 1.5 // 1 | 0 end)
case("random_range", function() local r = math.random(1, 10); local f = math.random(); return r >= 1 and r <= 10 and math.type(r), f >= 0 and f < 1 end)
return report()
