case("time_type", function() local t = os.time(); return math.type(t), t > 1700000000 end)
case("time_table", function() return os.time({ year = 2026, month = 9, day = 17, hour = 12, min = 30, sec = 15 }) end)
case("time_table_default_hour", function() return os.time({ year = 2026, month = 1, day = 1 }) end)
case("time_normalise", function() return os.time({ year = 2026, month = 14, day = 35, hour = 12 }) end)
case("time_missing_field", function() return os.time({ year = 2026 }) end)
case("date_utc_fmt", function() return os.date("!%Y-%m-%dT%H:%M:%SZ", 1789000000) end)
case("date_utc_table", function() return os.date("!*t", 1789000000) end)
case("date_fields", function() return os.date("!%a %A %b %B %d %j %p %y %%", 1789000000) end)
case("date_c_x", function() return os.date("!%c | %x | %X | %D | %F | %T | %R", 1789000000) end)
case("date_default_fmt_type", function() return type(os.date()) end)
case("date_invalid_conv", function() return os.date("%Ez", 0) end)
case("date_invalid_conv2", function() return os.date("%Q", 0) end)
case("date_epoch", function() return os.date("!%Y-%m-%d %H:%M:%S", 0) end)
case("date_negative", function() return os.date("!%Y-%m-%d", -86400) end)
case("difftime", function() return os.difftime(10, 4), math.type(os.difftime(10, 4)) end)
case("clock_type", function() return math.type(os.clock()), os.clock() >= 0 end)
case("roundtrip", function() local t = os.date("!*t", 1789000000); t.isdst = nil; return os.date("!%H:%M", os.time(t) ) ~= nil end)
return report()
