case("d", function() return string.format("%d %5d %-5d| %05d %+d", 42, 42, 42, 42, 42) end)
case("d_float_int", function() return string.format("%d", 3.0) end)
case("d_float_frac", function() return string.format("%d", 3.5) end)
case("s", function() return string.format("%s %10s %-10s| %.2s", "x", "right", "left", "truncate") end)
case("s_nonstring", function() return string.format("%s %s %s %s", 1, 1.5, true, nil) end)
case("s_tostring_meta", function() return string.format("%s", setmetatable({}, { __tostring = function() return "custom" end })) end)
case("q", function() return string.format("%q", 'he said "hi"\n') end)
case("q_num", function() return string.format("%q %q", 1, 0.5) end)
case("f", function() return string.format("%f %.2f %10.3f %.0f", 3.14159, 3.14159, 3.14159, 2.5) end)
case("g", function() return string.format("%g %g %g %g", 1e20, 0.1, 100000, 1e-5) end)
case("e", function() return string.format("%e %.2E", 12345.678, 0.00012) end)
case("x", function() return string.format("%x %X %#x %08x", 255, 255, 255, 255) end)
case("x_negative", function() return string.format("%x", -1) end)
case("o_c", function() return string.format("%o %c%c", 8, 72, 105) end)
case("a", function() return string.format("%a", 1.0) end)
case("i", function() return string.format("%i", 7) end)
case("percent", function() return string.format("100%%") end)
case("missing_arg", function() return string.format("%d") end)
case("bad_spec", function() return string.format("%y", 1) end)
case("string_to_d", function() return string.format("%d", "10") end)
case("method_form", function() return ("%s=%d"):format("k", 1) end)
case("iso8601", function() return string.format("%04d-%02d-%02dT%02d:%02d:%02dZ", 2026, 9, 17, 4, 5, 6) end)
return report()
