case("find_plain", function() return string.find("a.b.c", ".", 1, true), string.find("hello", "l"), string.find("hello", "xyz"), string.find("hello", "") end)
case("find_init", function() return string.find("hello hello", "hello", 2), string.find("abc", "b", -1), string.find("abc", "c", -1) end)
case("find_captures", function() return string.find("key=value", "(%w+)=(%w+)") end)
case("match_aturi", function() return string.match("at://did:plc:abc/app.bsky.feed.post/3kabc", "^at://([^/]+)/([^/]+)/(.+)$") end)
case("match_literal_prefix", function() return string.match("literal:self", "^literal:(.+)$"), string.match("tid", "^literal:(.+)$") end)
case("match_classes", function() return string.match("  x1_y  ", "^%s*(.-)%s*$"), string.match("2026-09-17T10:20:30Z", "(%d+)-(%d+)-(%d+)T(%d+):(%d+):(%d+)") end)
case("match_position_capture", function() return string.match("hello", "()ll()") end)
case("match_frontier", function() return string.match("THE (quick) fox", "%f[%a]%a+", 5), string.gsub("hello world", "%f[%w]%w+", string.upper) end)
case("match_balanced", function() return string.match("f(a(b)c)d", "%b()") end)
case("match_backref", function() return string.match([[say "hi" ok]], [[(["'])(.-)%1]]) end)
case("match_sets", function() return string.match("abc-123", "[%a]+"), string.match("abc-123", "[^%a]+"), string.match("a]b", "[]]"), string.match("x-y", "[a%-z]+", 2) end)
case("match_quantifiers", function() return string.match("aaa", "a-"), string.match("aaa", "a*"), string.match("aaa", "a+"), string.match("aaa", "a?"), string.match("", "a*") end)
case("match_anchor", function() return string.match("abc", "^b"), string.match("abc", "c$"), string.match("a$c", "a$c") end)
case("gsub_string", function() return string.gsub("hello world", "o", "0"), string.gsub("hello", "", "-"), string.gsub("abc", "%w", "%0%0"), string.gsub("hello world", "(%w+) (%w+)", "%2 %1") end)
case("gsub_limit", function() return string.gsub("aaaa", "a", "b", 2) end)
case("gsub_table", function() return string.gsub("$name is $age", "%$(%w+)", { name = "Ann", age = 30 }) end)
case("gsub_function", function() return string.gsub("a1b22", "%d+", function(d) return "<" .. #d .. ">" end), string.gsub("abc", "b", function() return nil end), string.gsub("abc", "b", function() return false end) end)
case("gsub_percent", function() return string.gsub("50%", "%%", " percent"), string.gsub("a.b", "%.", "%%") end)
case("gsub_bad_repl", function() return string.gsub("abc", "b", "%2") end)
case("gmatch", function() local out = {}; for k, v in string.gmatch("a=1, b=2", "(%w+)=(%w+)") do out[#out + 1] = k .. v end; return out end)
case("gmatch_words", function() local out = {}; for w in ("one two  three"):gmatch("%S+") do out[#out + 1] = w end; return out end)
case("gmatch_empty", function() local n = 0; for _ in string.gmatch("abc", "") do n = n + 1 end; return n end)
case("malformed_pattern", function() return string.find("a", "[a") end)
case("malformed_pattern2", function() return string.find("a", "%") end)
case("url_encode", function() return (string.gsub("a b&c", "[^%w]", function(c) return string.format("%%%02X", string.byte(c)) end)) end)
case("split", function() local out = {}; for part in string.gmatch("a,b,,c", "([^,]*)") do out[#out + 1] = part end; return out end)
return report()
