case("insert_remove", function() local t = { 1, 2, 3 }; table.insert(t, 4); table.insert(t, 1, 0); local a = table.remove(t); local b = table.remove(t, 1); return t, a, b, table.remove({}), #t end)
case("insert_bad_pos", function() local t = { 1 }; table.insert(t, 5, "x") end)
case("insert_wrong_args", function() table.insert({}, 1, 2, 3) end)
case("concat", function() return table.concat({ 1, 2, "x", 2.5 }, ", "), table.concat({}, ","), table.concat({ "a", "b", "c" }, "-", 2, 3), table.concat({ "a" }) end)
case("concat_bad", function() return table.concat({ 1, {}, 3 }) end)
case("sort_default", function() local t = { 3, 1, 2.5, -1 }; table.sort(t); return t end)
case("sort_strings", function() local t = { "b", "a", "C" }; table.sort(t); return t end)
case("sort_cmp", function() local t = { 3, 1, 2 }; table.sort(t, function(a, b) return a > b end); return t end)
case("sort_by_field", function() local t = { { n = 2 }, { n = 1 }, { n = 3 } }; table.sort(t, function(a, b) return a.n < b.n end); return t[1].n, t[2].n, t[3].n end)
case("sort_mixed_err", function() local t = { 1, "a" }; table.sort(t) end)
case("sort_invalid_order", function() local t = {}; for i = 1, 50 do t[i] = i % 7 end; return pcall(table.sort, t, function() return true end) ~= nil end)
case("unpack_pack", function() local p = table.pack(1, nil, 3); return p.n, table.unpack({ 1, 2, 3 }), table.unpack({ 1, 2, 3 }, 2), table.unpack({ 1, 2, 3 }, 2, 3) end)
case("move", function() local t = table.move({ 1, 2, 3 }, 1, 3, 2); return t, table.move({ 1, 2 }, 1, 2, 1, {}) end)
case("length_border", function() local t = { 1, 2, 3 }; t[#t + 1] = 4; t[#t] = nil; return #t, #{ n = 1 }, #{ 1, 2, nil }, #"abc" end)
case("next_pairs", function() local t = { a = 1 }; local k, v = next(t); local k2 = next(t, k); return k, v, k2, next({}) end)
case("next_invalid_key", function() return next({}, "nope") end)
case("pairs_order_array", function() local out = {}; for k, v in pairs({ 10, 20, 30 }) do out[#out + 1] = k .. ":" .. v end; return out end)
case("pairs_modify_during", function() local t = { a = 1, b = 2, c = 3 }; for k in pairs(t) do t[k] = nil end; return next(t) end)
case("ipairs_stops_at_nil", function() local n = 0; for _ in ipairs({ 1, 2, nil, 4 }) do n = n + 1 end; return n end)
case("ipairs_meta_index", function() local t = setmetatable({}, { __index = function(_, i) if i <= 3 then return i * 10 end end }); local s = 0; for _, v in ipairs(t) do s = s + v end; return s end)
case("pairs_meta", function() local t = setmetatable({}, { __pairs = function(t) return function(_, k) if not k then return 1, "one" end end, t, nil end }); local out = {}; for k, v in pairs(t) do out[#out + 1] = k .. v end; return out end)
case("nil_key", function() local t = {}; t[nil] = 1 end)
case("nan_key", function() local t = {}; t[0 / 0] = 1 end)
case("nil_index_read", function() local t = {}; return t[nil] end)
case("constructor", function() local function mr() return 1, 2, 3 end; local t = { mr(), mr() }; local u = { mr(), (mr()) }; local v = { [1] = "a", "b"; x = 1 }; return #t, #u, v[1], v.x end)
case("select", function() return select("#"), select("#", nil, nil), select(2, "a", "b", "c"), select(-1, "a", "b", "c") end)
case("select_bad", function() return select(0, "a") end)
case("rawequal_rawlen", function() local t = setmetatable({ 1, 2 }, { __len = function() return 99 end }); return #t, rawlen(t), rawlen("abc"), rawequal(t, t), rawequal("a", "a") end)
return report()
