case("utf8_char_len", function() return utf8.char(72, 8364, 128512), utf8.len("h€😀"), utf8.len("\xff") end)
case("utf8_codepoint", function() return utf8.codepoint("h€", 1, -1) end)
case("utf8_codes", function() local out = {}; for p, c in utf8.codes("a€") do out[#out + 1] = p .. ":" .. c end; return out end)
case("utf8_offset", function() return utf8.offset("a€b", 3), #utf8.charpattern end)
case("type_names", function() return type(nil), type(1), type("s"), type({}), type(print), type(true) end)
case("tostring_table_prefix", function() return string.sub(tostring({}), 1, 7), string.sub(tostring(print), 1, 9) end)
case("version", function() return _VERSION end)
case("g_self", function() return _G._G == _G, _G.string == string end)
case("env_upvalue", function() local _ENV = { tostring = tostring }; return tostring(x) end)
case("integer_string_keys_json_shape", function() local t = { [1] = "a", [2] = "b", [4] = "d" }; return #t == 2 or #t == 4 end)
case("print_exists", function() return type(print) end)
case("load_exists", function() return type(load), type(loadstring), type(dofile), type(require) end)
case("load_chunk", function() local f = load("return 1 + 1"); return f() end)
case("load_env", function() local f = load("return x", "chunk", "t", { x = 5 }); return f() end)
case("load_syntax_error", function() local f, e = load("return +"); return f, type(e) end)
return report()
