case("vararg_basic", function() local function f(...) return select("#", ...), ... end; return f(), f(1), f(nil, nil), f(1, nil) end)
case("vararg_table", function() local function f(...) local t = { ... }; return #t, t[2] end; return f("a", "b", "c") end)
case("vararg_pack_n", function() local function f(...) return table.pack(...).n end; return f(nil, nil, nil) end)
case("vararg_passthrough", function() local function g(method, nsid, ...) return pcall(method, nsid, ...) end; return g(function(a, b, c) return a .. b .. c end, "x", "y", "z") end)
case("vararg_adjust", function() local function f(...) local a, b = ...; return a, b end; return f(1), (f(1, 2)) end)
case("vararg_middle", function() local function f(...) return ..., "end" end; return f(1, 2, 3) end)
case("multi_return_adjust", function() local function mr() return 1, 2, 3 end; local a, b, c, d = mr(); local t = { mr(), 10 }; return a, b, c, d, #t, (mr()) end)
case("closure_counter", function() local function mk() local n = 0; return function() n = n + 1; return n end end; local c1, c2 = mk(), mk(); c1(); c1(); return c1(), c2() end)
case("closure_loop_fresh", function() local fns = {}; for i = 1, 3 do fns[i] = function() return i end end; return fns[1](), fns[2](), fns[3]() end)
case("closure_shared_upvalue", function() local x = 0; local function inc() x = x + 1 end; local function get() return x end; inc(); inc(); return get() end)
case("iife_multi", function() local a, b, c = (function() return 1, 2, 3 end)(); return a, b, c end)
case("recursion_local", function() local function fact(n) if n <= 1 then return 1 end return n * fact(n - 1) end; return fact(20), fact(21) end)
case("tail_call_deep", function() local function loop(n) if n == 0 then return "done" end return loop(n - 1) end; return loop(100000) end)
case("method_sugar", function() local o = { v = 3 }; function o:add(n) self.v = self.v + n; return self end; return o:add(1):add(2).v end)
case("and_or", function() return nil or "d", false or nil, 0 and "zero truthy", "" and "empty truthy", nil and 1, 1 and nil or "x" end)
case("multiple_assign", function() local a, b = 1, 2; a, b = b, a; local t = { 1, 2 }; local i = 1; i, t[i] = i + 1, 20; return a, b, i, t[1], t[2] end)
case("repeat_scope", function() local n = 0; repeat local done = n >= 2; n = n + 1 until done; return n end)
case("numeric_for_var_assign", function() local out = {}; for i = 1, 3 do local j = i; j = j * 2; out[#out + 1] = j end; return out end)
case("shadowing", function() local x = 1; do local x = 2; x = x + 1 end; return x end)
case("integer_keys_string_keys", function() local t = {}; t[1] = "int"; t["1"] = "str"; return t[1], t["1"] end)
case("long_comment", function() --[[ multi
line ]] --[==[ another ]==] return "ok" end)
return report()
